### ISSUE TITLE
Confusing code this.log in matrix 3

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST325#28]
I'm not sure what this code does?  This was already in the assignment for matrix3, but it appears as though the ranges are outside the range of a 3X3 matrix.

Maybe this was a copy paste error?   

I'm thinking a 3X3 matrix should only have element values of 0,1,2,3,4,5,6,7 and 8

Not sure if I should care, but below just seems odd.

// -------------------------------------------------------------------------
	this.log = function() {
		var e = this.elements;
		console.log('[ '+
					'\n ' + e[0]  + ', ' + e[1]  + ', ' + e[2]  +
			        '\n ' + e[4]  + ', ' + e[5]  + ', ' + e[6]  +
			        '\n ' + e[8]  + ', ' + e[9]  + ', ' + e[10] +
			        '\n ' + e[12] + ', ' + e[13] + ', ' + e[14] +
			        '\n]'
		);

**Comment by Mcghee-Jake** [comment]
hmmm.... yeah I'm not sure what this is about. My guess is that the professor was using this to test something while making it and forgot to modify this part.

**Comment by mdoussias** [comment]
Doesn't matter anyway.  Just curious.
