### ISSUE TITLE
INVERSE

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST325#29]
REGARDING INVERSE in MATRIX3

I'm getting this close to completed, but something is wrong.  Going to put it away for now and try to find my error later.

this.inverse = function() {
		// todo
		// modify 'this' matrix so that it becomes its inverse
		var e = this.elements;
		var t = this.clone().elements;   //This clone is a temporary clone of the matrix we are trying to inverse t for temporary.
		var d = ((e[0]*e[4]*e[8]) + (e[1] * e[5] * e[6]) + (e[2] * e[3] * e[7]) ) - ((e[2] * e[4] * e[6]) + (e[0] * e[5] * e[7]) + (e[1] * e[3] * e[8])); //Find the determinant
		
		//Todo need to check for zero value determinants
		
		// Replace values with the inverese value
		this.elements[0] = -(1/d)*((t[4]*t[8])-(t[5]*t[7]));   
		this.elements[1] = -(1/d)*((t[1]*t[8])-(t[2]*t[7]));
		this.elements[2] = -(1/d)*((t[1]*t[5])-(t[2]*t[4]));
		this.elements[3] = -(1/d)*((t[3]*t[8])-(t[5]*t[6]));
		this.elements[4] = -(1/d)*((t[0]*t[8])-(t[6]*t[2]));
		this.elements[5] = -(1/d)*((t[0]*t[5])-(t[2]*t[3]));
		this.elements[6] = -(1/d)*((t[3]*t[7])-(t[6]*t[4]));
		this.elements[7] = -(1/d)*((t[0]*t[7])-(t[1]*t[6]));
		this.elements[8] = -(1/d)*((t[0]*t[4])-(t[1]*t[3]));
		
		return this.elements;
	};

**Comment by Mcghee-Jake** [comment]
Not entirely sure how you are going about getting the inverse. Maybe if we reference the same thing we might be able to figure it out?

this is what I have. It's a lot to digest. Though I think it should work it doesn't. I'm going to have to test each component step by step to see where I went wrong.

        this.inverse = function() {
		// modify 'this' matrix so that it becomes its inverse
	
		// calculate the matrix of minors
		var matrixOfMinors = calcMatrixOfMinors();
		
		// turn the matrix of minors into the matrix of cofactors
		var cofactorMatrix = matrixOfMinorsToCofactorMatrix(matrixOfMinors);
		
		// turn the matrix of cofactors into the adjugate matrix
		var adjugateMatrix = cofactorMatrixToAdjugateMatrix(cofactorMatrix);
		
		var inverseMatrix = new Float32Array(9);
		inverseMatrix[0] = adjugateMatrix[0] / determinant();
		inverseMatrix[1] = adjugateMatrix[1] / determinant();
		inverseMatrix[2] = adjugateMatrix[2] / determinant();
		inverseMatrix[3] = adjugateMatrix[3] / determinant();
		inverseMatrix[4] = adjugateMatrix[4] / determinant();
		inverseMatrix[5] = adjugateMatrix[5] / determinant();
		inverseMatrix[6] = adjugateMatrix[6] / determinant();
		inverseMatrix[7] = adjugateMatrix[7] / determinant();
		inverseMatrix[8] = adjugateMatrix[8] / determinant();
		
		this.elements = inverseMatrix;
		
		return this;
	};
	
	// helper function for inverse
	// calculates the matrix of minors for a 3x3 matrix
	calcMatrixOfMinors = function() {
		var minor0 = new Float32Array(4);
		minor0[0] = this.elements[4];
		minor0[1] = this.elements[5];
		minor0[2] = this.elements[7];
		minor0[3] = this.elements[8];
		
		var minor1 = new Float32Array(4);
		minor1[0] = this.elements[3];
		minor1[1] = this.elements[5];
		minor1[2] = this.elements[6];
		minor1[3] = this.elements[8];
		
		var minor2 = new Float32Array(4);
		minor2[0] = this.elements[3];
		minor2[1] = this.elements[4];
		minor2[2] = this.elements[6];
		minor2[3] = this.elements[7];
		
		var minor3 = new Float32Array(4);
		minor3[0] = this.elements[1];
		minor3[1] = this.elements[2];
		minor3[2] = this.elements[7];
		minor3[3] = this.elements[8];
		
		var minor4 = new Float32Array(4);
		minor4[0] = this.elements[0];
		minor4[1] = this.elements[2];
		minor4[2] = this.elements[6];
		minor4[3] = this.elements[8];
		
		var minor5 = new Float32Array(4);
		minor5[0] = this.elements[0];
		minor5[1] = this.elements[1];
		minor5[2] = this.elements[6];
		minor5[3] = this.elements[7];
		
		var minor6 = new Float32Array(4);
		minor6[0] = this.elements[1];
		minor6[1] = this.elements[2];
		minor6[2] = this.elements[4];
		minor6[3] = this.elements[5];
		
		var minor7 = new Float32Array(4);
		minor7[0] = this.elements[0];
		minor7[1] = this.elements[2];
		minor7[2] = this.elements[3];
		minor7[3] = this.elements[5];
		
		var minor8 = new Float32Array(4);
		minor8[0] = this.elements[0];
		minor8[1] = this.elements[1];
		minor8[2] = this.elements[3];
		minor8[3] = this.elements[4];
		
		var matrixOfMinors = new Float32Array(9);
		matrixOfMinors[0] = minorDeterminant(minor0);
		matrixOfMinors[1] = minorDeterminant(minor1);
		matrixOfMinors[2] = minorDeterminant(minor2);
		matrixOfMinors[3] = minorDeterminant(minor3);
		matrixOfMinors[4] = minorDeterminant(minor4);
		matrixOfMinors[5] = minorDeterminant(minor5);
		matrixOfMinors[6] = minorDeterminant(minor6);
		matrixOfMinors[7] = minorDeterminant(minor7);
		matrixOfMinors[8] = minorDeterminant(minor8);
		
		return matrixOfMinors;
	};

	// helper function for inverse
	// calculates the determinate for a 2x2 matrix
	minorDeterminant = function(minor) {
		return minor[0] * minor[3] - minor[1] * minor[2];
	};
	
	// helper function for inverse
	// converts a 3x3 matrix of minors into a cofactor matrix
	matrixOfMinorsToCofactorMatrix = function(matrixOfMinors) {
		var cofactorMatrix = new Float32Array(9);
		
		for (var i = 0; i < 9; i++) {
			if (i % 2 == 0) {
				cofactorMatrix[i] = matrixOfMinors[i];
			} else {
				cofactorMatrix[i] = matrixOfMinors[i] * -1;
			}
		}
		
		return cofactorMatrix;
	};
	
	// helper function for inverse
	// converts a 3x3 cofactor matrix into an adjugate matrix
	// this is almost identical to transpose, except it does not alter the elements of 'this'
	cofactorMatrixToAdjugateMatrix = function(cofactorMatrix) {
		var transposed = new Float32Array(9);
		
		transposed[0] = cofactorMatrix[0];
		transposed[3] = cofactorMatrix[1];
		transposed[6] = cofactorMatrix[2];
		transposed[1] = cofactorMatrix[3];
		transposed[4] = cofactorMatrix[4];
		transposed[7] = cofactorMatrix[5];
		transposed[2] = cofactorMatrix[6];
		transposed[5] = cofactorMatrix[7];
		transposed[8] = cofactorMatrix[8];
		
		return transposed;
	};

**Comment by Mcghee-Jake** [comment]
I guess my math was right but my I needed to added 'this.' in front of all the functions. Anyways I got inverse working now.
