### ISSUE TITLE
TRANSPOSE  Matrix3

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST325#30]
This code should work for transpose function  but I'm experiencing some issues.  
Will fix in a bit.

// -------------------------------------------------------------------------
	this.transpose = function() {
		// modify 'this' matrix so that it becomes its transpose.  
		// To transpose something is to reflect it across its diagonal
		//
		// Example Before         	Example After
		// reflection			  	Reflection
		// |0 1 2|          	  	|0 3 6|	
		// |3 4 5| 					|1 4 7|
		// |6 7 8|					|2 5 8|
 		//
		this.transpose = function() {
		var e = this.elements;
		var tempElement;  					// Temporarily holds the value of the element

		tempElement = e[1]; e[1] = e[3]; e[3] = tempElement; 
		tempElement = e[2]; e[2] = e[6]; e[6] = tempElement;
		tempElement = e[5]; e[5] = e[7]; e[7] = tempElement;
		
		return this;
	};

**Comment by Mcghee-Jake** [comment]
I went with a different approach and got it working.
