### ISSUE TITLE
Column Width and Height improvement

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST325#37]
Time permitting, change the column width 768 and hieeght 512 to constants.  

Constants  are better to use.

**Comment by mdoussias** [comment]
I didn't change it yet because not sure how the code will be affected in the TODO 3 thru 10

**Comment by Mcghee-Jake** [comment]
I changed it to      
          var canvas = document.getElementById("webgl-canvas");
	  var width = canvas.width;
	  var height = canvas.height;
		
         gl.viewport(0, 0, width, height);
